site_name: Hypercubing
site_url: https://hypercubing.xyz/
docs_dir: docs/
repo_name: Hypercubers/hypercubing.xyz
repo_url: https://github.com/Hypercubers/hypercubing.xyz
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.follow
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  icon:
    edit: material/pencil
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hypercubers
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xxFvfyx89p
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - abbr
  - attr_list
  - footnotes
  - pymdownx.caret
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - smarty
  - tables
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/symbol_replace.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - glightbox:
      auto_caption: true
  - awesome-nav
  - redirects:
      redirect_maps:
        "discord.md": "https://discord.gg/xxFvfyx89p"
        "theory/grip_theory.md": "theory/grip-theory.md"
        "leaderboards/index.md": "https://lb.hypercubing.xyz"
        "leaderboards/rules.md": "leaderboard-rules.md"
        "leaderboards/aggregate.md": "https://lb.hypercubing.xyz"
        "leaderboards/history.md": "https://lb.hypercubing.xyz"
        "leaderboards/other-leaderboards.md": "external-links.md"
        "leaderboards/records.md": "https://lb.hypercubing.xyz"
        "leaderboards/submit.md": "https://lb.hypercubing.xyz/submit-solve"
        "leaderboards/solvers/tetrian.md": "https://lb.hypercubing.xyz/solver?id=4"
        "leaderboards/solvers/connor.md": "https://lb.hypercubing.xyz/solver?id=5"
        "leaderboards/solvers/rowan.md": "https://lb.hypercubing.xyz/solver?id=6"
        "leaderboards/solvers/grant.md": "https://lb.hypercubing.xyz/solver?id=7"
        "leaderboards/solvers/hactar.md": "https://lb.hypercubing.xyz/solver?id=8"
        "leaderboards/solvers/hyperespy.md": "https://lb.hypercubing.xyz/solver?id=9"
        "leaderboards/solvers/luna.md": "https://lb.hypercubing.xyz/solver?id=10"
        "leaderboards/solvers/alvin.md": "https://lb.hypercubing.xyz/solver?id=11"
        "leaderboards/solvers/weill.md": "https://lb.hypercubing.xyz/solver?id=12"
        "leaderboards/solvers/adam.md": "https://lb.hypercubing.xyz/solver?id=13"
        "leaderboards/solvers/koen.md": "https://lb.hypercubing.xyz/solver?id=14"
        "leaderboards/solvers/cubedude.md": "https://lb.hypercubing.xyz/solver?id=15"
        "leaderboards/solvers/kevin.md": "https://lb.hypercubing.xyz/solver?id=16"
        "leaderboards/solvers/asa.md": "https://lb.hypercubing.xyz/solver?id=17"
        "leaderboards/solvers/yuste.md": "https://lb.hypercubing.xyz/solver?id=18"
        "leaderboards/solvers/gray.md": "https://lb.hypercubing.xyz/solver?id=19"
        "leaderboards/solvers/olaf.md": "https://lb.hypercubing.xyz/solver?id=20"
        "leaderboards/solvers/void.md": "https://lb.hypercubing.xyz/solver?id=21"
        "leaderboards/solvers/markk.md": "https://lb.hypercubing.xyz/solver?id=22"
        "leaderboards/solvers/origamist.md": "https://lb.hypercubing.xyz/solver?id=23"
        "leaderboards/solvers/tymofro.md": "https://lb.hypercubing.xyz/solver?id=24"
        "leaderboards/solvers/edan.md": "https://lb.hypercubing.xyz/solver?id=25"
        "leaderboards/solvers/myigiter.md": "https://lb.hypercubing.xyz/solver?id=26"
        "leaderboards/solvers/battistin.md": "https://lb.hypercubing.xyz/solver?id=27"
        "leaderboards/solvers/danielcohen.md": "https://lb.hypercubing.xyz/solver?id=28"
        "leaderboards/solvers/ethandavis.md": "https://lb.hypercubing.xyz/solver?id=29"
        "leaderboards/solvers/pkearth.md": "https://lb.hypercubing.xyz/solver?id=30"
        "leaderboards/solvers/milojacquet.md": "https://lb.hypercubing.xyz/solver?id=31"
        "leaderboards/solvers/akkei.md": "https://lb.hypercubing.xyz/solver?id=32"
        "leaderboards/solvers/godly.md": "https://lb.hypercubing.xyz/solver?id=33"
        "leaderboards/solvers/jackcai.md": "https://lb.hypercubing.xyz/solver?id=34"
        "leaderboards/solvers/bilal.md": "https://lb.hypercubing.xyz/solver?id=35"
        "leaderboards/solvers/stella.md": "https://lb.hypercubing.xyz/solver?id=36"
        "leaderboards/solvers/vin.md": "https://lb.hypercubing.xyz/solver?id=37"
        "leaderboards/solvers/rayzchen.md": "https://lb.hypercubing.xyz/solver?id=38"
        "leaderboards/solvers/saturnb.md": "https://lb.hypercubing.xyz/solver?id=39"
        "leaderboards/solvers/pistelli.md": "https://lb.hypercubing.xyz/solver?id=40"
        "leaderboards/solvers/hana.md": "https://lb.hypercubing.xyz/solver?id=41"
        "leaderboards/solvers/lorenzo.md": "https://lb.hypercubing.xyz/solver?id=42"
        "leaderboards/solvers/starry.md": "https://lb.hypercubing.xyz/solver?id=43"
        "leaderboards/solvers/pkmnhx.md": "https://lb.hypercubing.xyz/solver?id=44"
        "leaderboards/solvers/pickle.md": "https://lb.hypercubing.xyz/solver?id=45"
        "leaderboards/solvers/josie.md": "https://lb.hypercubing.xyz/solver?id=46"
        "leaderboards/solvers/kliu.md": "https://lb.hypercubing.xyz/solver?id=47"
        "leaderboards/solvers/nenri.md": "https://lb.hypercubing.xyz/solver?id=48"
        "leaderboards/solvers/gstout.md": "https://lb.hypercubing.xyz/solver?id=49"
        "leaderboards/solvers/cali.md": "https://lb.hypercubing.xyz/solver?id=50"
        "leaderboards/solvers/jessica.md": "https://lb.hypercubing.xyz/solver?id=51"
        "leaderboards/solvers/bruh.md": "https://lb.hypercubing.xyz/solver?id=52"
        "leaderboards/solvers/ysinx.md": "https://lb.hypercubing.xyz/solver?id=53"
        "leaderboards/solvers/vigoprins.md": "https://lb.hypercubing.xyz/solver?id=54"
        "leaderboards/solvers/minidog.md": "https://lb.hypercubing.xyz/solver?id=55"
        "leaderboards/solvers/messil.md": "https://lb.hypercubing.xyz/solver?id=56"
        "leaderboards/solvers/voytxt.md": "https://lb.hypercubing.xyz/solver?id=57"
        "leaderboards/solvers/emca.md": "https://lb.hypercubing.xyz/solver?id=58"
hooks:
  - hooks/feature_matrix.py
  - hooks/symbol_hooks.py
validation:
  absolute_links: relative_to_docs
  anchors: warn
  unrecognized_links: warn
